### ISSUE TITLE
How to use this JS library to crop images?

### ISSUE THREAD

**Issue by MojtabaTajik** [img-js/mini-canvas-editor#1]
Hello,
Firstly, I'd like to commend you on creating such a lightweight and intuitive tool – it's impressive!

I'm considering integrating this library into a web app for basic photo editing functionalities. Based on the README, it seems this library supports image cropping. However, when I load an image, I couldn't find the tool or option for cropping. Could you please guide me on how this functionality works or if there's a specific way to access it?

Thank you in advance!

**Comment by b4rtaz** [comment]
Hello @MojtabaTajik! Please check [this online example](https://img-js.github.io/mini-canvas-editor/webpack-app/public/crop.html) ([source code](https://github.com/img-js/mini-canvas-editor/blob/main/demos/webpack-app/src/crop.ts)).

**Comment by MojtabaTajik** [comment]
Ok, So it's tricky. What happens if the user opens two photos and wants to crop one of them and then collage them?

**Comment by b4rtaz** [comment]
@MojtabaTajik that example show how to use the mini canvas editor only for cropping a single photo, that's why the sidebar is hidden. If you want to use the editor for more complex use cases then you need to turn on the sidebar with the layers panel and the properties panel. Then your user may compose the image as he wants.

```ts
		const editor = Editor.createFromImage(
			placeholder,
			image,
			{
				workspaceHeight: 160,
				workspaceWidth: 200,
				fitToWorkspace: true,
				select: true
			},
			{
				initialMode: EditorMode.select,
                                // ...
				sidebar: {
					layers: true,
					properties: true
				}
			}
		);
```
