### ISSUE TITLE
Add Layer via Code - Image 

### ISSUE THREAD

**Issue by hryan49** [img-js/mini-canvas-editor#2]
How can we add an image layer automatically from code without using the interface upload button?

**Comment by b4rtaz** [comment]
Hello @hryan49!

Something like this:

```ts
import { MceImage } from 'mini-canvas-core';

const editor = Editor.createBlank(/* ... */);

// ...

const image = new Image();
image.src = './assets/cat.jpg';
image.onload = () => {
    const mceImage = new MceImage(image, { left: 0, top: 0 });
    editor.add(mceImage);
};
```

**Comment by hryan49** [comment]
Excellent thank you. This works from node. 
How is this possible from client side Javascript leveraging 0.1.1/dist/index.umd.js?

**Comment by b4rtaz** [comment]
@hryan49 to use the above code with pure JS you need to update to 0.2.0 version (this version requires two <script> tags, check the readme file). Then you need to add prefixes:

```js
const editor = miniCanvasEditor.Editor.createBlank(/* ... */);

// ...

const mceImage = new miniCanvasCore.MceImage(image, { left: 0, top: 0 });
```
