### ISSUE TITLE
API Documentation?

### ISSUE THREAD

**Issue by anthonyeden** [img-js/mini-canvas-editor#5]
Hello,
This looks like a really cool project! Do you have any API documentation available? Things I'm looking at doing in particular:

* How can I export an image template to some sort of JSON object so I can parse it myself and render server-side?
* Is there documentation showing how to turn features on/off? e.g. turn off paint brush, add/remove fonts, etc?

Thanks!

**Comment by b4rtaz** [comment]
Hello @anthonyeden!

The API documentation doesn't exist yet. But you can learn a lot from examples.

> How can I export an image template to some sort of JSON object so I can parse it myself and render server-side?

Check the [svelte demo](https://github.com/img-js/mini-canvas-editor/tree/main/demos/svelte-app), there you can find an example how to render images in the backend.

> Is there documentation showing how to turn features on/off? e.g. turn off paint brush

The [crop example](https://img-js.github.io/mini-canvas-editor/webpack-app/public/crop.html) has disabled almost all features in the toolbox. 

>  add/remove fonts, etc?

This is not configurable yet. Fill free to open a merge request. The `EditorConfiguration` type should be extended.
