### ISSUE TITLE
Run project in local

### ISSUE THREAD

**Issue by zsoltjanes** [img-js/mini-canvas-editor#6]
Hi all! First of all Its very nice package! 

I would like to run this code in my local dev environment but it shows many errors. I want to change the code a bit how can I start the developer mode locally? 

I installed the pnpm. In root folder I run the `build `command. What would be the order of the commands?

**Comment by b4rtaz** [comment]
Hello @zsoltjanes, it seems you used a newer PNPM (7.x was expected). I upgraded PNPM to 9.x and it seems the workflow [works](https://github.com/img-js/mini-canvas-editor/actions/runs/11090656333/job/30813271607) on GitHub correctly.
