### ISSUE TITLE
Trying to add fill image to replacer

### ISSUE THREAD

**Issue by seven7seven** [img-js/mini-canvas-editor#7]
https://github.com/img-js/mini-canvas-editor/commit/47ba2bb1cdd0d7e7d21b4bfdd6cbe3f22ef20236

But I cannot, for the life of me, build the project.

I tried running "scripts/publish.sh", or manually running npm run build after installing dependencies and pnpm, but in both cases, the dist/ folder is not generated, only some index.umd.js files are generated in core/dist/ and editor/dist/.

Can you please offer some insights as to how to build the project?

Much appreciated!

**Comment by b4rtaz** [comment]
Hello @seven7seven,

to run this repository locally you need:

1. install packages `pnpm install` (I'm using `pnpm -v` => `9.8.0`)
2. in the first terminal run `pnpm serve`
3. in the second terminal run `pnpm build`

This should build all packages and demos, for example on `http://127.0.0.1:4333/demos/webpack-app/public/crop.html` you should see the crop demo.

If you need the hot reload, then ignore the [3] point and open 3 terminals and run:

```
terminal 1> cd editor && pnpm start
terminal 2> cd demos/webpack-app && pnpm start
terminal 3> cd demos/svelte-app && pnpm start
```

**Comment by seven7seven** [comment]
Thanks, using pnpm fixed a lot if build errors, crop demo runs just fine locally.

But I'm still having one big issue. Running above commands doesn't generate /dist/ folder in project root. I think this causes my next issues.

In another package.json I'm doing:

```
"dependencies": {
    "mini-canvas-editor": "file:../mini-canvas-editor",
},
```

It seems to resolve and symlinks just fine, but then I'm getting these errors when building w/ webpack:

```
ERROR in ./assets/js/share/design-center.js 1:0-66
Module not found: Error: Can't resolve '../../../node_modules/mini-canvas-editor' in '/Users/catalinpintea/code/crmrebs/assets/js/share'

ERROR in ./assets/js/share/design-center.js 2:0-87
Module not found: Error: Can't resolve '../../../node_modules/mini-canvas-core' in '/Users/catalinpintea/code/crmrebs/assets/js/share'

ERROR in ./assets/js/share/design-center.js 4:0-65
Module not found: Error: Can't resolve '../../../node_modules/mini-canvas-editor/css/editor.css' in '/Users/catalinpintea/code/crmrebs/assets/js/share'
```

This works fine with "mini-canvas-editor: 0.3.0" btw, but not with the local build.

Thank you!

**Comment by b4rtaz** [comment]
The path should be:

```
"mini-canvas-editor": "file:../mini-canvas-editor/editor"
```

The dist files are placed in the `editor` folder.

**Comment by b4rtaz** [comment]
BTW: I noticed that the dependencies in the webpack demo were incorrect, so I [fixed them](https://github.com/img-js/mini-canvas-editor/commit/4b730079979f12880ec8750a61254649f4381a49).

**Comment by seven7seven** [comment]
Thank you!

And thanks for the nudge in the right direction, ended up leaving the path as it was, and altering the import as follows:

```
import { Editor } from '../../../../mini-canvas-editor/editor';
import { MceTextbox, MceRect, MceImage } from '../../../../mini-canvas-editor/core';

import '../../../../mini-canvas-editor/editor/css/editor.css';
```

There's probably an elegant way avoiding relative paths but this is temporary.
